const pdf = (id, title, tags, focus) => ({ id, title, author: "Campaign reference PDF", focus, tags });

export const CAMPAIGN_SOURCEBOOKS = [
  {
    id: "custom-gm-operating-instructions",
    title: "155 ABY GM Operating Instructions",
    author: "Campaign archive: gm.md",
    focus: "Run a sandbox Star Wars tabletop campaign in 155 ABY, seventeen years beyond the published Legacy-era endpoint. Treat the setting's post-138 ABY history as original campaign material, keep continuity consistent, react to player choices, and remain in an authentic Star Wars register. Track factions, debts, locations, injuries, relationships, and consequences. Use the supplied 155 ABY conversion and economy references as binding house rules.",
    tags: ["155 ABY", "GM", "Campaign Bible", "Legends"],
  },
  {
    id: "custom-155-aby-reconciliation",
    title: "155 ABY System Reconciliation",
    author: "Campaign house rules",
    focus: "The campaign uses one Saga-style d20 resolution engine. WEG material is descriptive and inspirational only. Convert WEG attributes into the Saga ability that governs the situation, convert dice ratings into appropriate Saga training and level, convert Force Points into Saga Force Points, and convert Character Points into normal Saga advancement. Never import a second dice-pool, Force Point, or advancement system.",
    tags: ["155 ABY", "House Rules", "Conversion", "Saga d20"],
  },
  {
    id: "custom-155-aby-equipment-credits",
    title: "155 ABY Equipment & Credits",
    author: "Campaign house rules",
    focus: "Currency is regional and political: Imperial Credits near Fel-controlled space, CSA Scrip in corporate sectors, IGFED Standard Notes across reconstruction markets, Hutt Trade Chits in Hutt space, and barter or favors in deep Rim and Force-adept communities. Exchange rates are plot hooks. Background and career determine starting resources, and every character begins with one signature possession whose story matters more than its statistics. Equipment should be introduced through availability, debts, restrictions, and consequences. Lightsabers are earned or built in play, never treated as ordinary shop inventory.",
    tags: ["155 ABY", "Economy", "Equipment", "IGFED", "CSA", "Hutts"],
  },
  {
    id: "custom-star-wars-terminology",
    title: "Star Wars Terminology & Immersion Lexicon",
    author: "Campaign language standard, informed by active sourcebooks and public Star Wars reference terminology",
    focus: "Use credits, credit chips, dataries, scrip, trade chits, and local currency instead of dollars or generic money. Use starship, freighter, shuttle, hyperspace, hyperlane, astrogation, comlink, datapad, HoloNet, HoloNet News, Coruscant News Network, Galactic News Network, slicer, blaster, medcenter, bacta, syndicate, sector, district, and level where appropriate. Translate player shorthand silently and preserve intent. Never call the Force magic, a starship a spaceship when a more specific term is known, or a slicer a hacker in in-character narration. Regional and faction-specific terminology is preferred over a single universal vocabulary.",
    tags: ["Immersion", "Terminology", "Coruscant", "Currency", "Continuity"],
  },
  {
    id: "custom-155-aby-news-networks",
    title: "155 ABY News Network Editorial Roles",
    author: "Campaign continuity reference; informed by HoloNet News, Coruscant News Network, and Galactic News Network",
    focus: "Use three distinct in-world media lenses on current events. HoloNet News is the primary galaxy-wide, state-sanctioned service: it carries official notices, security messaging, reconstruction updates, and propaganda shaped by whichever authorities control the relay infrastructure. Coruscant News Network is an inner-world political broadcaster focused on the capital, Senate maneuvering, corporate influence, district security, and Core institutions. Galactic News Network is a broad regional organization whose correspondents report across systems, often carrying local witnesses and incomplete but useful accounts. News must reflect the 155 ABY campaign state, current location, faction pressure, and player consequences. No feed is perfectly objective; contradictions are intentional leads, not random errors. Use HoloNet News for official framing, Coruscant News Network for political framing, and Galactic News Network for regional texture and stories that official channels omit.",
    tags: ["155 ABY", "HoloNet News", "Coruscant News Network", "Galactic News Network", "Media", "Continuity"],
  },
  {
    id: "custom-rpg-system-bible-155-aby",
    title: "RPG System Bible — AI Game Master Edition (155 ABY Adaptation)",
    author: "Supplied Instructions (2).pdf; adapted campaign reference",
    focus: "Use this as a GM procedure reference for a persistent, immersive, consequence-driven 155 ABY campaign. Maintain an in-universe default mode, remember player choices, faction states, Force alignment, bounties, infamy, NPC relationships, active arcs, and regional consequences. Simulate factions with goals, resources, awareness, and countermeasures; use NPC tiers from disposable scene figures through recurring contacts, rivals, and faction leaders; and let NPC tactics adapt to D'mir's history. Scale resistance and complications proportionally to notoriety, faction awareness, Force alignment, galaxy momentum, resources, and the character's current Saga Edition level. Use the supplied narrative outcome bands as private guidance only, then adjudicate through the campaign's single Saga Edition chassis. Treat the Force as an active moral and narrative pressure that can produce visions, guidance, danger, or environmental disturbance, but never grant unearned powers. NVIDIA is the primary AI test engine for GM adjudication, NPC dialogue, scene flavor, HoloNet reports, continuity, and world-state updates. It must use the campaign's Saga rules and validated update format; the saved campaign ledger records accepted consequences. Adapt the document to the established D'mir campaign: do not restart character creation, do not require image generation, and do not assume Supabase or any external persistence service. The existing 155 ABY world ledger remains the continuity record.",
    tags: ["155 ABY", "GM Procedures", "Faction AI", "Force Resonance", "NPC Tiers", "NVIDIA"],
  },
  pdf("saga-edition-core-rulebook", "Saga Edition Core Rulebook", ["Saga Edition", "Rules", "Character Creation"], "Primary rules authority for the campaign's Saga Edition mechanics. Exact wording must be checked against a reviewed page before asserting a rule."),
  pdf("revised-core-rulebook", "Revised Core Rulebook", ["Pre-Saga", "Setting", "Character Ideas"], "Earlier d20 edition. Use for setting, character, and adventure inspiration only; do not import mechanics into the Saga Edition rules chassis."),
  pdf("knights-old-republic-campaign-guide", "Knights of the Old Republic Campaign Guide", ["KOTOR", "Ancient History", "Jedi", "Sith"], "Use for ancient Jedi and Sith traditions, Republic and Mandalorian legacies, relics, ideological echoes, and archaeological or Force-related plot hooks. Present ancient material as recovered history, distorted legend, or dangerous technology in 155 ABY."),
  pdf("jedi-academy-training-manual", "Jedi Academy Training Manual", ["Jedi", "Training", "Force"], "Use for Jedi instruction, lightsaber disciplines, Force traditions, trials, mentorship, rival schools, and the social cost of training. Adapt any mechanics into the campaign's Saga engine and make advanced abilities earned through play."),
  pdf("galaxy-of-intrigue", "Galaxy of Intrigue", ["Intrigue", "Politics", "Espionage", "Social Conflict"], "Use for layered conspiracies, negotiations, intelligence operations, faction maneuvering, blackmail, betrayals, and social encounters where information is a resource. Build scenes around competing motives rather than simple good-versus-evil checks."),
  pdf("galaxy-at-war", "Galaxy at War", ["War", "Factions", "Mass Conflict", "Military"], "Use for military campaigns, fronts, occupation, logistics, command decisions, resistance cells, and the consequences of war on civilians. Keep the player character's choices connected to strategic fallout without turning every scene into a battle map."),
  pdf("arms-and-equipment-guide", "Arms and Equipment Guide", ["Equipment", "Weapons", "Armor", "Gear"], "Use for the look, availability, reputation, legality, and narrative function of weapons, armor, tools, explosives, and specialist gear. Convert stats into the local Saga rules and make restricted equipment create heat or obligations."),
  pdf("coruscant-core-worlds", "Coruscant and the Core Worlds", ["Locations", "Coruscant", "Politics", "Core"], "Use for dense urban worlds, institutions, class divisions, elite politics, bureaucracy, crime under surveillance, trade routes, and Core-world cultural texture. Coruscant should feel layered: official power above, hidden economies below."),
  pdf("galactic-campaign-guide", "Galactic Campaign Guide", ["Campaigns", "Factions", "Galaxy", "Worldbuilding"], "Use as a broad campaign-planning reference for eras, galactic-scale factions, organizations, conflicts, and sandbox arcs. Let large forces create pressure while preserving player agency and local consequences."),
  pdf("heros-guide", "Hero's Guide", ["Heroes", "Character Options", "Destiny"], "Use for character identity, heroic archetypes, motivations, talents, destinies, and memorable signature capabilities. Reward choices that reveal who the character is, not only choices that maximize tactical success."),
  pdf("ultimate-alien-anthology", "Ultimate Alien Anthology", ["Species", "Cultures", "NPCs", "Aliens"], "Use for species diversity, physiology, customs, naming, communities, prejudice, and alien NPC characterization. Give every introduced NPC a motive and specific cultural texture without reducing a species to a stereotype."),
  pdf("geonosis-outer-rim-worlds", "Geonosis and the Outer Rim Worlds", ["Locations", "Outer Rim", "Geonosis", "Frontier"], "Use for frontier worlds, industrial scars, hive societies, remote settlements, local power brokers, dangerous travel, and the economic realities of the Rim. Make distance, supply, and local custom matter."),
  pdf("ultimate-adversaries", "Ultimate Adversaries", ["Adversaries", "NPCs", "Creatures", "Factions"], "Use for adversary concepts, encounter roles, criminal figures, military threats, creatures, and unusual antagonists. Adapt opposition to the character's current capability and give enemies goals, resources, and escape routes."),
  pdf("unknown-regions", "The Unknown Regions", ["Unknown Regions", "Exploration", "Mystery", "Frontier"], "Use for navigation beyond familiar charts, isolated cultures, hidden powers, anomalous worlds, lost routes, and exploration mysteries. Keep the unknown genuinely uncertain and seed clues before revealing major truths."),
  pdf("threats-of-the-galaxy", "Threats of the Galaxy", ["Threats", "Villains", "Creatures", "Disasters"], "Use for escalating threats, villainous organizations, hazards, monsters, and campaign-level dangers. Threats should change the situation even when the players win and should have understandable motives or operating patterns."),
  pdf("starships-of-the-galaxy", "Starships of the Galaxy", ["Starships", "Travel", "Combat", "Smuggling"], "Use for ship silhouettes, roles, manufacturers, crews, modifications, chase scenes, travel complications, and the social meaning of a vessel. Treat ship debt, maintenance, ownership, and who recognizes the hull as more important than a bare stat block."),
  pdf("galactic-maps", "Galactic Maps", ["Maps", "Navigation", "Travel", "Locations"], "Use the supplied galactic map archive as a spatial reference for routes, hyperspace distance, border pressure, chokepoints, remote systems, and travel complications. Do not assume travel is instantaneous; make route choice and navigation part of play."),
  pdf("force-unleashed-campaign-guide", "The Force Unleashed Campaign Guide", ["Force", "Imperial Era", "Rebellion", "Secrets"], "Use for clandestine Force users, Imperial hunters, secret apprentices, resistance networks, moral pressure, and the consequences of power used in secret. Keep Force abilities costly, visible, and connected to the character's choices."),
  pdf("scum-and-villainy", "Scum and Villainy", ["Underworld", "Crime", "Smuggling", "Hutts"], "Use for syndicates, smugglers, bounty work, fences, safehouses, debt, betrayals, criminal etiquette, and the unstable alliances of the underworld. Criminal credits and favors should open doors while creating obligations."),
  pdf("scavengers-guide-to-droids", "Scavenger's Guide to Droids", ["Droids", "Technology", "Scavengers", "Equipment"], "Use for droid personalities, repair culture, illicit modifications, salvage, autonomy, memory, ownership, and the legal or ethical status of artificial beings. Droids should have preferences and history, not function only as equipment."),
  pdf("gamemaster-screen", "Star Wars Gamemaster Screen", ["GM Tools", "Tables", "Improvisation", "Reference"], "Use as a quick-reference aid for encounter pacing, conditions, difficulty guidance, NPC generation, hazards, and table-side improvisation. It supports the Saga engine but never overrides the campaign's custom conversion rules."),
  pdf("legacy-era-campaign-guide", "Legacy Era Campaign Guide", ["Legacy Era", "155 ABY", "Fel Empire", "Jedi"], "Primary historical bridge into the campaign's 155 ABY setting. Use Fel-era politics, post-Imperial institutions, Jedi legacy, Imperial remnants, galactic borders, and unresolved conflicts as the recent history that shapes every current faction."),
];

export const CAMPAIGN_SOURCEBOOK_IDS = new Set(CAMPAIGN_SOURCEBOOKS.map((book) => book.id));
