export const SYNDICATES = [
  {
    id: "black-sun",
    name: "Black Sun",
    type: "Criminal syndicate",
    territories: ["Coruscant lower levels", "Nar Shaddaa", "Outer Rim routes"],
    specialties: ["Contraband", "Assassination", "Information brokerage", "Coercion"],
    description: "An old and adaptable criminal network whose cells survive by compartmentalization, patronage, and selective brutality.",
    economicBase: "Smuggling lanes, protection agreements, illicit finance, and high-value intelligence.",
    risk: "Extreme",
    accessCost: 75,
    color: "#e23b3b",
    npcs: [
      { name: "Vexa Nahl", species: "Zabrak", role: "Black Sun cell broker", purpose: "Rebuild a profitable Coruscant intelligence cell without attracting Imperial scrutiny.", method: "Trades verified favors, then weaponizes every secret learned.", vulnerability: "Her younger brother is hidden in a debt colony on Ord Mantell." },
      { name: "Dargo Senn", species: "Human", role: "Retired Vigo's enforcer", purpose: "Find the Black Sun faction that ordered his former patron's assassination.", method: "Uses prison contacts, surgical intimidation, and old codes of silence.", vulnerability: "He refuses work that risks civilian children, a weakness rivals exploit." },
    ],
      storyPatterns: ["A customs official takes a discreet inspection fee for every shipment.", "A cell uses a public bounty to conceal a private assassination.", "An ambitious broker falsifies accounts to make a rival cell look disloyal."],
      internalConflict: "Cell brokers want profit and deniability; older enforcers want blood and repayment.",
  },
  {
    id: "hutt-cartel",
    name: "Hutt Cartel",
    type: "Kajidic confederation",
    territories: ["Nal Hutta", "Nar Shaddaa", "Hutt Space"],
    specialties: ["Freight", "Gambling", "Indenture", "Debt enforcement"],
    description: "A web of kajidics bound by profit, custom, and grudges rather than a single chain of command.",
    economicBase: "Port fees, spice and arms routes, gambling houses, debt contracts, and bonded labor.",
    risk: "High",
    accessCost: 100,
    color: "#c084fc",
    npcs: [
      { name: "Morga the Hutt", species: "Hutt", role: "Kajidic factor of Nar Shaddaa", purpose: "Turn disputed freight lanes into a private revenue stream before rival kajidics notice.", method: "Offers protection, hospitality, and contracts written to become debts.", vulnerability: "A rival has proof that Morga diverted tribute during a succession dispute." },
      { name: "Salla Venn", species: "Twi'lek", role: "Debt registrar and protocol broker", purpose: "Buy her family's freedom from a generational kajidic obligation.", method: "Finds lawful loopholes and quietly recruits capable outsiders.", vulnerability: "Her forged release papers can expose the entire account network." },
    ],
    storyPatterns: ["A port authority is secretly owned by a kajidic through layered debt.", "A gambling house offers a favor that becomes a binding obligation.", "A disputed cargo causes two kajidics to threaten war while publicly honoring a truce."],
    internalConflict: "Kajidics cooperate when profit demands it, then sabotage one another over tribute, face, and succession.",
  },
  {
    id: "tenloss",
    name: "Tenloss Syndicate",
    type: "Arms and logistics network",
    territories: ["Mid Rim", "Outer Rim", "Corporate Sector margins"],
    specialties: ["Weapons", "Mercenary logistics", "Discreet transport", "Corporate espionage"],
    description: "A disciplined weapons-and-services network favored by clients who need deniable logistics without a kajidic oath.",
    economicBase: "Arms brokerage, convoy security, component diversion, and private contracts.",
    risk: "High",
    accessCost: 125,
    color: "#f59e0b",
    npcs: [
      { name: "Koro Venn", species: "Mandalorian", role: "Tenloss contract marshal", purpose: "Keep the network independent from Hutt and corporate control.", method: "Tests clients with strict terms, then honors contracts exactly.", vulnerability: "He is carrying a disputed clan debt that could void his authority." },
      { name: "Ilyra Quell", species: "Pantoran", role: "Logistics director", purpose: "Move relief cargo through blockaded systems while concealing weapons shipments.", method: "Builds layered manifests and pays crews before they know the full route.", vulnerability: "A captured ledger links her to a respected humanitarian convoy." },
    ],
    storyPatterns: ["A legal cargo contract hides a weapons diversion.", "A mercenary escort must choose between the contract and stranded civilians.", "A corporate client demands deniable violence while refusing to acknowledge the network."],
    internalConflict: "Contract officers demand discipline; field crews resent clients who treat them as disposable assets.",
  },
  {
    id: "bounty-hunters-guild",
    name: "Bounty Hunters' Guild",
    type: "Licensed contract association",
    territories: ["Major ports", "Hutt Space", "Imperial jurisdictions"],
    specialties: ["Recovery", "Tracking", "Apprehension", "Protective contracts"],
    description: "A loose professional association whose legitimacy varies by jurisdiction and whose members guard their reputations fiercely.",
    economicBase: "Posted bounties, recovery fees, escort retainers, and verified contract work.",
    risk: "Variable",
    accessCost: 50,
    color: "#4fd8e8",
    npcs: [
      { name: "Jax Ordo", species: "Human", role: "Guild route adjudicator", purpose: "Keep bounty contracts verifiable so the Guild survives government pressure.", method: "Demands proof, witnesses, and clean chain-of-custody records.", vulnerability: "He has quietly voided a contract placed by a powerful Imperial client." },
      { name: "Nira Vask", species: "Twi'lek", role: "Independent bounty hunter", purpose: "Clear her name after a rival hunter falsified a kill confirmation.", method: "Takes difficult recovery work and lets results speak for her.", vulnerability: "Her ship is impounded under a technical customs charge." },
    ],
    storyPatterns: ["A posted bounty is lawful but morally compromised.", "A hunter must prove a target is alive before a rival claims the fee.", "A local official manipulates the contract registry for political revenge."],
    internalConflict: "Guild legitimacy depends on procedure, but independent hunters survive by bending procedure without being caught.",
  },
  {
    id: "red-key-raiders",
    name: "Red Key Raiders",
    type: "Pirate and raider coalition",
    territories: ["Outer Rim shipping lanes", "Frontier depots", "Unpatrolled hyperspace"],
    specialties: ["Piracy", "Salvage", "Hostage-taking", "Route disruption"],
    description: "A loose frontier coalition that turns weak convoy protection and disputed salvage claims into revenue.",
    economicBase: "Captured cargo, salvage rights, ransom, and route tolls.",
    risk: "Extreme",
    accessCost: 150,
    color: "#fb7185",
    npcs: [
      { name: "Captain Rusk Tal", species: "Weequay", role: "Raid flotilla captain", purpose: "Unite the raiders long enough to seize a permanent refueling station.", method: "Uses spectacle, hostage leverage, and selective mercy to build a legend.", vulnerability: "His crew suspects he lost the coordinates to the station years ago." },
      { name: "Mira Kest", species: "Duros", role: "Salvage claims broker", purpose: "Convert disputed wrecks into legitimate salvage before the CSA can seize them.", method: "Sells competing claims to different buyers and keeps the best evidence hidden.", vulnerability: "A living survivor from her largest salvage operation knows the truth." },
    ],
    storyPatterns: ["A raider crew calls a hostage a rescued passenger until the ransom arrives.", "A salvage claim becomes a territorial dispute when the wreck contains military technology.", "A captain stages a pirate attack to conceal an internal mutiny."],
    internalConflict: "Captains want autonomy; crews want reliable shares; prisoners and passengers become bargaining pieces.",
  },
  {
    id: "exchange",
    name: "The Exchange",
    type: "Legacy criminal network",
    territories: ["Industrial worlds", "Smuggler ports", "Old Republic underworld routes"],
    specialties: ["Slicing", "Droid trafficking", "Loans", "Urban rackets"],
    description: "A fractured but persistent criminal tradition whose local bosses borrow the name when it serves their leverage.",
    economicBase: "Predatory loans, stolen technology, illicit labor, and data markets.",
    risk: "High",
    accessCost: 90,
    color: "#a78bfa",
    npcs: [
      { name: "Tavik Renn", species: "Mirialan", role: "Exchange data-lender", purpose: "Reassemble a local Exchange chapter from the ruins of an old Sith-era network.", method: "Uses predatory loans, slicer apprentices, and favors hidden in droid code.", vulnerability: "His resurrection project depends on one missing master cipher." },
      { name: "Kessa-9", species: "Modified protocol droid", role: "Contract auditor", purpose: "Prove that the Exchange's debt records were altered by an unknown patron.", method: "Quotes every clause exactly and blackmails only when necessary.", vulnerability: "A memory partition contains an identity it was ordered to forget." },
    ],
    storyPatterns: ["A loan is offered through a droid intermediary with a hidden collateral clause.", "A slicer job exposes the client rather than the target.", "A local boss claims the Exchange name while another faction holds the real account books."],
    internalConflict: "Traditional debt houses want control; younger slicers want information to replace physical territory.",
  },
  {
    id: "corporate-sector-authority",
    name: "Corporate Sector Authority",
    type: "Chartered autonomous authority",
    territories: ["Corporate Sector"],
    specialties: ["Contract enforcement", "Security", "Industrial concessions", "Debt collection"],
    description: "Not a street gang, but a sovereign commercial power whose private security and contract courts can function like a syndicate at the frontier.",
    economicBase: "Charters, tariffs, concessions, bonded labor, and industrial monopolies.",
    risk: "Institutional",
    accessCost: 200,
    color: "#94a3b8",
    npcs: [
      { name: "Director Pell Arveth", species: "Human", role: "CSA concession magistrate", purpose: "Expand lawful corporate jurisdiction without triggering a Galactic Alliance inquiry.", method: "Uses contracts, audits, and security warrants instead of open violence.", vulnerability: "His promotion rests on a refinery concession with falsified casualty figures." },
      { name: "Surn Dala", species: "Neimoidian", role: "Private security liaison", purpose: "Prevent labor unrest from interrupting a profitable reconstruction corridor.", method: "Offers incentives first, then makes examples through debt courts.", vulnerability: "A workers' cooperative has evidence of his off-ledger payments." },
    ],
    storyPatterns: ["A permit office becomes a protection racket under a lawful tariff schedule.", "Private security creates the crisis it was hired to contain.", "A debt court sentences a character using a contract they never knowingly signed."],
    internalConflict: "Managers seek quarterly stability; local security chiefs profit from disorder that justifies their budgets.",
  },
  {
    id: "mandalorian-clan-networks",
    name: "Mandalorian Clan Networks",
    type: "Clan and mercenary alliances",
    territories: ["Mandalore", "Clan enclaves", "Frontier contracts"],
    specialties: ["Escort", "Mercenary work", "Recovery", "Beskar trade"],
    description: "Not a criminal syndicate by default; clan obligations, contracts, and reputation determine whether outsiders are treated as clients or liabilities.",
    economicBase: "Security contracts, salvage, metallurgy, and clan-backed trade.",
    risk: "Conditional",
    accessCost: 175,
    color: "#22d3ee",
    npcs: [
      { name: "Kara Vhett", species: "Human", role: "Clan envoy and contract negotiator", purpose: "Secure work that funds a clan's resettlement without selling its honor.", method: "Tests courage, preparation, and the exact wording of an oath.", vulnerability: "Her clan's stolen beskar relic is being used as leverage by a rival." },
      { name: "Torr Vizsla", species: "Mandalorian", role: "Recovery captain", purpose: "Recover a missing clan heir before a Hutt broker sells the trail.", method: "Tracks matériel, witnesses, and reputation across several systems.", vulnerability: "He owes a life-debt to the very syndicate he distrusts." },
    ],
    storyPatterns: ["A contract is technically valid but dishonorable under clan custom.", "A recovered heir refuses the clan role their rescuers expect.", "A beskar shipment creates a dispute between commerce, inheritance, and oath."],
    internalConflict: "Clan honor, survival economics, and individual loyalty do not always point to the same target.",
  },
];

export function getSyndicateEconomy(syndicate, gameState, now = Date.now()) {
  const relation = Number(gameState.syndicateRelations?.[syndicate.id] || 0);
  const cycle = Math.sin(now / 3600000 + syndicate.id.length) * 8;
  const access = Math.max(0, Math.min(100, 50 + relation));
  const weeklyVolume = Math.round((120000 + syndicate.name.length * 8500) * (1 + cycle / 100));
  const heat = Math.max(0, Math.min(100, 50 - relation + (gameState.notoriety || 0) * 0.35));
  return { relation, access, weeklyVolume, heat, netPosition: relation >= 20 ? "favorable" : relation <= -20 ? "hostile" : "uncommitted" };
}
