import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { expect, it } from "vitest";

it("restores a checkpoint into an independent timeline without rewriting the original", async () => {
  process.env.CAMPAIGN_DB_PATH = join(mkdtempSync(join(tmpdir(), "galaxy-branches-")), "test.sqlite");
  const store = await import("./campaign-store");
  const original = store.getCampaign();
  expect(original.era).toBe("150 ABY");
  expect(original.character).toBeNull();
  const { checkpoint } = store.createCheckpoint(original.id, "Before change");
  store.appendScene(original.id, "A later scene");
  const branch = store.restoreCheckpoint(checkpoint.id);
  expect(branch.id).not.toBe(original.id);
  expect(branch.currentScene).toBe(original.currentScene);
  expect(branch.parentTimelineId).toBe(original.id);
  expect(branch.events[0].kind).toBe("restore");
  expect(branch.checkpoints).toEqual([]);
  expect(store.getCampaign().id).toBe(branch.id);
  expect(store.getCampaign(original.id).currentScene).toBe("A later scene");
  expect(() => store.restoreCheckpoint(checkpoint.id)).toThrow();
  store.selectTimeline(original.id);
  expect(store.getCampaign().currentScene).toBe("A later scene");
  expect(store.listTimelines()).toHaveLength(2);
  const beforeNote = store.getCampaign();
  const withNote = store.playerCommand({ campaignId: beforeNote.id, revision: beforeNote.revision, command: "add_note", title: "Personal plan", detail: "Find work without joining a faction" });
  expect(withNote.world?.journal[0].kind).toBe("note");
  expect(withNote.events[0].summary).toContain("journal note");
  expect(() => store.playerCommand({ campaignId: beforeNote.id, revision: beforeNote.revision, command: "add_note", title: "Duplicate", detail: "Retry" })).toThrow("changed");
  expect(store.getCampaign().world?.journal).toHaveLength(1);
  const revision = store.getCampaign().revision!;
  expect(() => store.mutateCampaign(beforeNote.id, revision, state => { state.title = "CORRUPTED"; throw new Error("rollback"); })).toThrow();
  expect(store.getCampaign().title).not.toBe("CORRUPTED");
  const stale = store.getCampaign();
  const saved = store.createCheckpoint(stale.id, "Versioned checkpoint", stale.revision);
  expect(() => store.createCheckpoint(stale.id, "Stale save", stale.revision)).toThrow("changed");
  store.selectTimeline(branch.id);
  const restoredFromExplicitTimeline = store.restoreCheckpoint(saved.checkpoint.id, saved.campaign.id, saved.campaign.revision);
  expect(restoredFromExplicitTimeline.parentTimelineId).toBe(stale.id);
});
